// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {
	user_session_url: ():string => {
		return '/users/sign_in.json';
	},
};