// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {
	api_users_current_path: (): string => {
		return "/api/users/current";
	},
	/** not correct but good enough for testing */
	api_users_current_url: (): string => {
		return "/api/users/current";
	},
};